add required input var
tags module was using the build input var, but it was not defined.
This was producing failures like:
Error: Reference to undeclared input variable

  on ../../infra/terraform/modules/tags/output.tf line 7, in locals:
   7:     "build" : var.build

An input variable with the name "build" has not been declared. This variable
can be declared with a variable "build" {} block.